#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
version="${1:-0.1}"
label="${2:-preview}"
package_name="thoth-$version-$label"
dist_root="${THOTH_DIST_ROOT:-$repo_root/dist}"
package_dir="$dist_root/$package_name"
hub_dir="$repo_root/hub"

commands=(
  "review-api:thoth-review-api"
  "ingest:thoth-ingest"
  "review-cli:thoth-review-cli"
)

targets=(
  "darwin:arm64"
  "darwin:amd64"
  "linux:amd64"
)

require_command() {
  local name="$1"
  if ! command -v "$name" >/dev/null 2>&1; then
    echo "missing required command: $name" >&2
    exit 1
  fi
}

write_run_script() {
  cat > "$package_dir/scripts/run-thoth.sh" <<'SCRIPT'
#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root="$(cd "$script_dir/.." && pwd)"
os="$(uname -s | tr '[:upper:]' '[:lower:]')"
machine="$(uname -m)"

case "$machine" in
  x86_64|amd64) arch="amd64" ;;
  arm64|aarch64) arch="arm64" ;;
  *) echo "unsupported architecture: $machine" >&2; exit 1 ;;
esac

case "$os" in
  darwin|linux) ;;
  *) echo "unsupported OS: $os" >&2; exit 1 ;;
esac

binary="$root/bin/thoth-review-api-$os-$arch"
if [[ ! -x "$binary" ]]; then
  echo "missing executable for $os/$arch: $binary" >&2
  exit 1
fi

export THOTH_ROOT="$root"
exec "$binary" "$@"
SCRIPT
  chmod +x "$package_dir/scripts/run-thoth.sh"
}

write_doctor_script() {
  cat > "$package_dir/scripts/doctor-thoth.sh" <<'SCRIPT'
#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root="$(cd "$script_dir/.." && pwd)"

echo "Thoth root: $root"
echo
echo "Binaries:"
find "$root/bin" -maxdepth 1 -type f -print | sort
echo
echo "Docs:"
find "$root/lib/docs" -maxdepth 1 -type f -print | sort
echo
echo "Runtime directories:"
for path in data data/db data/imports data/cases data/quarantine data/exports data/tmp logs; do
  if [[ -d "$root/$path" ]]; then
    echo "ok  $path"
  else
    echo "new $path"
  fi
done
SCRIPT
  chmod +x "$package_dir/scripts/doctor-thoth.sh"
}

write_readme() {
  cat > "$package_dir/README.md" <<README
# Thoth $version $label

This is a Thoth preview package for local analyst review and public testing.
It is not a finished 1.0 release.

## Start the UI

\`\`\`bash
./scripts/run-thoth.sh
\`\`\`

Then open:

\`\`\`text
http://127.0.0.1:8080
\`\`\`

Use synthetic or approved lab SEKER bundles only. Do not use real endpoint data for public validation.

## Included Binaries

- \`bin/thoth-review-api-<os>-<arch>\`
- \`bin/thoth-ingest-<os>-<arch>\`
- \`bin/thoth-review-cli-<os>-<arch>\`

## Runtime Data

Thoth creates mutable runtime data under:

- \`data/\`
- \`logs/\`
- \`tmp/\`

Do not commit runtime data, imported bundles, SQLite databases, or exported investigations unless they are synthetic and intentionally documented.
README
}

write_validation() {
  cat > "$package_dir/VALIDATION.md" <<VALIDATION
# Thoth $version $label Validation

Generated by \`packaging/hub/build-thoth.sh\`.

## Required Before Promotion

- [ ] \`scripts/check.sh\` passes from the source repo root.
- [ ] macOS build starts the local UI and shows the home page.
- [ ] Linux amd64 build starts the local UI inside a clean Linux VM and shows the home page.
- [ ] Synthetic sample SEKER bundle ingests through the UI.
- [ ] Case page renders Host Overview, findings, field decision, and notes.
- [ ] Save Bundle As... writes a \`thoth-investigation-*.tar.gz\`.
- [ ] Clear Current Investigation resets active data without deleting saved bundles.
- [ ] Load Investigation Bundle is either implemented and validated or clearly marked as not included.

## Scope Notes

- This package is a preview build, not Thoth 1.0.
- Windows is not a Thoth 0.1 target unless maintainers approve that scope.
- No baseline VM image is included or required.
VALIDATION
}

write_build_notes() {
  local stamp commit go_version host dirty
  stamp="$(date -u +%Y%m%dT%H%M%SZ)"
  commit="$(cd "$repo_root" && git rev-parse --short HEAD 2>/dev/null || echo unknown)"
  go_version="$(go version)"
  host="$(hostname 2>/dev/null || echo unknown)"
  dirty="false"
  if [[ -n "$(cd "$repo_root" && git status --short)" ]]; then
    dirty="true"
  fi

  cat > "$package_dir/BUILD_NOTES.md" <<NOTES
# Thoth $version $label Build Notes

- Package: \`$package_name\`
- Built at: \`$stamp\`
- Source commit: \`$commit\`
- Source tree dirty at build time: \`$dirty\`
- Build host: \`$host\`
- Go version: \`$go_version\`
- Output directory: \`$package_dir\`

## Build Targets

$(printf -- '- %s\n' "${targets[@]}")

## Commands

Built with:

\`\`\`bash
packaging/hub/build-thoth.sh $version $label
\`\`\`
NOTES
}

build_binaries() {
  mkdir -p "$package_dir/bin"
  for target in "${targets[@]}"; do
    local os arch
    os="${target%%:*}"
    arch="${target##*:}"
    for command in "${commands[@]}"; do
      local cmd_dir bin_name out
      cmd_dir="${command%%:*}"
      bin_name="${command##*:}"
      out="$package_dir/bin/$bin_name-$os-$arch"
      echo "building $bin_name for $os/$arch"
      (
        cd "$hub_dir"
        CGO_ENABLED=0 GOOS="$os" GOARCH="$arch" go build -trimpath -ldflags='-s -w' -o "$out" "./cmd/$cmd_dir"
      )
    done
  done
}

copy_docs() {
  mkdir -p "$package_dir/lib/docs"
  cp -p "$repo_root/docs/thoth-analyst-quick-start.md" "$package_dir/lib/docs/"
  cp -p "$repo_root/docs/thoth-quick-start.md" "$package_dir/lib/docs/"
  cp -p "$repo_root/docs/thoth-user-guide.md" "$package_dir/lib/docs/"
  cp -p "$repo_root/docs/thoth-platform-notes.md" "$package_dir/lib/docs/"
  cp -p "$repo_root/shared/contracts/bundle-layout.md" "$package_dir/lib/docs/"
}

write_checksums() {
  (
    cd "$package_dir"
    find . -type f \
      ! -path './SHA256SUMS.txt' \
      ! -path './data/*' \
      ! -path './logs/*' \
      ! -path './tmp/*' \
      -print | sort | sed 's#^\./##' | xargs shasum -a 256 > SHA256SUMS.txt
  )
}

make_archive() {
  (
    cd "$dist_root"
    rm -f "$package_name.tar.gz"
    tar -czf "$package_name.tar.gz" "$package_name"
  )
}

require_command go
require_command shasum
require_command tar

rm -rf "$package_dir"
mkdir -p "$package_dir/bin" "$package_dir/lib/docs" "$package_dir/scripts" "$package_dir/config" "$package_dir/logs" "$package_dir/data" "$package_dir/tmp"
mkdir -p "$package_dir/data/db" "$package_dir/data/imports" "$package_dir/data/cases" "$package_dir/data/quarantine" "$package_dir/data/exports" "$package_dir/data/tmp"

build_binaries
copy_docs
write_run_script
write_doctor_script
write_readme
write_validation
write_build_notes
write_checksums
make_archive

echo "Package: $package_dir"
echo "Archive: $dist_root/$package_name.tar.gz"
echo "Checksums: $package_dir/SHA256SUMS.txt"
